config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  namespace :admin do
    root 'home#index'

    get    :login,  to: 'sessions#new'
    post   :login,  to: 'sessions#create'
    delete :logout, to: 'sessions#destroy'

    resources :users, only: %i[index new create edit update destroy]
    resources :creators
    resources :works, param: :slug
  end
end

app/views/layouts/admin/_header.html.haml
%nav.navbar.navbar-expand-lg.navbar-dark.bg-primary
  = link_to 'yorozuya', admin_root_path, class: 'navbar-brand font-weight-bolder py-1'
  = button_tag type: :button, data: { toggle: :collapse, target: '#navbar-content' }, aria: { controls: 'navbar-content', expanded: :false }, class: 'navbar-toggler' do
    %span.navbar-toggler-icon
  .navbar-collapse.collapse#navbar-content
    .navbar-nav.mr-auto
      .d-lg-none= render 'layouts/admin/nav_menu'
    - if logged_in?
      .d-none.d-lg-inline.text-white.mr-2
        %i.fa.fa-user.fa-fw.fa-lg
        %span= current_user.name
      = link_to admin_logout_path, method: :delete, class: 'btn btn-sm btn-light text-primary d-block d-lg-inline-block mb-2 mb-lg-0' do
        %i.fa.fa-sign-out-alt.fa-fw
        = t('.logout')
    - else
      = link_to admin_login_path, class: 'btn btn-sm btn-light text-primary d-block d-lg-inline-block mb-2 mb-lg-0' do
        %i.fa.fa-sign-in-alt.fa-fw
        = t('.login')

app/views/layouts/admin/_nav_menu.html.haml
%ul.nav-menu
  %li
    = link_to admin_creators_path, class: nav_menu_classname(admin_creators_path) do
      %i.fa.fa-user.fa-lg.fa-fw
      = Creator.model_name.human
    = link_to admin_works_path, class: nav_menu_classname(admin_works_path) do
      %i.fa.fa-chess-board.fa-lg.fa-fw
      = Work.model_name.human
    = link_to admin_users_path, class: nav_menu_classname(admin_users_path) do
      %i.fa.fa-user-circle.fa-lg.fa-fw
      = User.model_name.human