config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  namespace :admin do
    root 'home#index'

    get    :login,  to: 'sessions#new'
    post   :login,  to: 'sessions#create'
    delete :logout, to: 'sessions#destroy'

    resources :users, only: %i[index new create edit update destroy]
    resources :creators
    resources :works, param: :slug
  end
end

app/models/work.rb
# == Schema Information
#
# Table name: works
#
#  id           :bigint           not null, primary key
#  like         :integer          default(0), not null
#  release_date :date             not null
#  slug         :string(255)      not null
#  status       :integer          default("draft"), not null
#  title        :string(255)      not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  work_id      :bigint
#
# Indexes
#
#  index_works_on_slug     (slug) UNIQUE
#  index_works_on_work_id  (work_id)
#
# Foreign Keys
#
#  fk_rails_...  (work_id => works.id)
#
class Work < ApplicationRecord
  EYE_CATCH_SIZES = { large: [1920, 1008], default: [1200, 630], thumb: [200, 105] }.freeze

  has_one_attached :eye_catch
  has_rich_text :content

  belongs_to :parent, class_name: 'Work', foreign_key: :work_id, optional: true, inverse_of: :parent

  has_many :children, class_name: 'Work', dependent: :nullify, inverse_of: :parent
  has_many :work_creators, -> { order(:xorder).order(:role) }, dependent: :destroy, inverse_of: :work
  has_many :creators, through: :work_creators

  accepts_nested_attributes_for :work_creators, reject_if: ->(attributes) { attributes[:role].blank? }, allow_destroy: true

  enum status: { draft: 0, published: 1 }

  validates :title, presence: true
  validates :status, presence: true
  validates :slug, presence: true, uniqueness: true
  validates :release_date, presence: true
  validates :like, presence: true
  validates :work_creators, length: { minimum: 1 }

  def to_param = slug
end

app/controllers/admin/works_controller.rb
class Admin::WorksController < Admin::ApplicationController
  before_action :set_new_work, only: %i[new]
  before_action :set_work, only: %i[show edit update destroy]
  before_action :build_work_creators, only: %i[new edit]

  def index
    @pagy, @works = pagy Work.includes(work_creators: { creator: { icon_attachment: :blob } }, eye_catch_attachment: :blob).order(release_date: :desc)
  end

  def show; end

  def new; end

  def create
    @work = Work.new(work_params)
    if @work.save
      redirect_to admin_work_path(@work), notice: t('admin.flash.create.success', model: Work.model_name.human)
    else
      build_work_creators if @work.work_creators.length.zero?
      render :new
    end
  end

  def edit; end

  def update
    if @work.update(work_params)
      @work.eye_catch.purge if params[:icon_destroy]
      redirect_to admin_work_path(@work), notice: t('admin.flash.update.success', model: Work.model_name.human)
    else
      build_work_creators if @work.work_creators.length.zero?
      render :edit
    end
  end

  def destroy
    if @work.destroy
      redirect_to admin_works_path, notice: t('admin.flash.destroy.success', model: Work.model_name.human)
    else
      redirect_back fallback_location: admin_works_path, notice: t('admin.flash.create.success', model: Work.model_name.human)
    end
  end

  private

  def work_params
    params.require(:work)
          .permit(:title, :status, :slug, :release_date, :content, :eye_catch, :work_id,
                  work_creators_attributes: %i[id guest role xorder creator_id name _destroy])
  end

  def set_new_work
    @work = Work.new
  end

  def set_work
    @work = Work.find_by!(slug: params[:slug])
  end

  def build_work_creators
    @work.work_creators.build(role: nil)
  end
end

app/views/admin/works/_creator_list.html.haml
- if work.work_creators.present?
  %ul.list-unstyled.list-wide.text-sm.mb-0
    - work.work_creators.includes(:creator).each do |work_creator|
      %li
        - if work_creator.guest?
          %span.icon--icon.bg-gray-light.d-inline-block.align-middle
          = t('admin.label.credit', role: work_creator.human_attribute_enum(:role), name: work_creator.name)
        - else
          = link_to admin_creator_path(work_creator.creator) do
            - if work_creator.creator.icon.attached?
              = image_tag work_creator.creator.icon.variant(resize: Creator::ICON_SIZES[:icon]), alt: t('admin.label.icon', name: work_creator.creator.name), class: 'icon--icon'
            - else
              %span.icon--icon.bg-gray-light.d-inline-block.align-middle
            = t('admin.label.credit', role: work_creator.human_attribute_enum(:role), name: work_creator.creator.name)

app/views/admin/works/_form.html.haml
= form_with model: [:admin, work], remote: true do |f|
  = render 'shared/errors', model: work
  .form-group
    = f.label :title, class: 'label--required'
    = f.text_field :title, class: 'form-control', required: true
  .form-group
    = f.label :work_id
    = f.collection_select :work_id, Work.where.not(id: work.id).order(:id), :id, :title, { include_blank: true }, class: 'form-control'
  .form-group
    = f.label :status, class: 'label--required'
    = f.collection_select :status, Work.statuses, :first, ->(w) { Work.human_attribute_enum_value :status, w.first }, {}, class: 'form-control', required: true
  .form-group
    = f.label :slug, class: 'label--required'
    = f.text_field :slug, class: 'form-control text-monospace', required: true
  .form-group
    = f.label :release_date, class: 'label--required'
    .form-date-select
      = f.date_select :release_date, { use_month_numbers: true, start_year: (Time.current - 100.years).year, end_year: Time.current.year, default: Time.current, date_separator: '<span></span>' }, class: 'form-control', required: true
  .form-group
    %legend.text-md.label--required= Work.human_attribute_name :work_creators
    .card.card-body.js-work-creator-fields
      %legend.mb-1
        .form-row.text-sm.d-none.d-sm-flex
          .col-1
            .d-xl-none= WorkCreator.human_attribute_name :guest
          .col-3= WorkCreator.human_attribute_name :role
          .col-3= WorkCreator.human_attribute_name :creator_id
          .col-3= WorkCreator.human_attribute_name :name
          .col-2= WorkCreator.human_attribute_name :xorder
      = f.fields_for :work_creators do |work_creator|
        = render 'work_creator_fields', f: work_creator, creators: Creator.order(:id)
      .mt-1
        = link_to_add_association f, :work_creators, render_options: { locals: { creators: Creator.order(:id) } }, class: 'btn btn-outline-primary' do
          %i.fa.fa-plus.fa-fw
          = t('.work_creator.add')
  .form-group
    %legend.text-md= Work.human_attribute_name :eye_catch
    .custom-file
      = f.file_field :eye_catch, class: 'custom-file-input', lang: :ja
      = f.label :eye_catch, class: 'custom-file-label custom-file-label-reverse' do
        %span
    - if work.eye_catch.attached?
      = image_tag work.eye_catch.variant(resize_to_fill: Work::EYE_CATCH_SIZES[:default]), alt: t('admin.label.eye_catch', title: work.title), class: 'eye-catch--default mt-2 mb-1'
      .custom-control.custom-checkbox
        = check_box_tag :icon_destroy, true, false, class: 'custom-control-input'
        = label_tag :icon_destroy, t('.icon_destroy'), class: 'custom-control-label'
  .form-group
    = f.label :content
    = f.rich_text_area :content
  = f.button type: :submit, class: 'btn btn-primary' do
    %i.fa.fa-check.fa-fw
    - if work.new_record?
      = t('admin.btn.create', model: Work.model_name.human)
    - else
      = t('admin.btn.update', model: Work.model_name.human)

app/views/admin/works/_table.html.haml
.table-responsive
  %table.table.table-bordered.table-middle
    %thead
      %tr
        %th ID
        %th= Work.human_attribute_name :title
        %th= Work.human_attribute_name :status
        %th= Work.human_attribute_name :slug
        %th= Work.human_attribute_name :release_date
        %th.d-none.d-md-table-cell= Work.human_attribute_name :work_creators
        %th= Work.human_attribute_name :like
        %th
    %tbody
      - works.each do |work|
        %tr{ class: work.draft? ? 'bg-gray-lightest' : '' }
          %th= work.id
          %td
            = link_to admin_work_path(work) do
              .font-weight-bold.pb-1= work.title
              - if work.eye_catch.attached?
                = image_tag work.eye_catch.variant(resize_to_fill: Work::EYE_CATCH_SIZES[:thumb]), alt: t('admin.label.eye_catch', title: work.title), class: 'eye-catch--thumb'
              - else
                %span.font-weight-bolder.text-sm NO IMAGE
          %td= work.human_attribute_enum :status
          %td
            %code.text-break= work.slug
          %td= l work.release_date if work.release_date.present?
          %td.d-none.d-md-table-cell= render 'admin/works/creator_list', work: work
          %td= work.like.to_s(:delimited)
          %td.table__td--with-buttons
            %ul.list-inline
              %li.list-inline-item
                = link_to edit_admin_work_path(work), class: 'btn btn-sm btn-outline-primary mb-1 mb-sm-0' do
                  %i.fa.fa-edit.fa-fw
                  = t('admin.btn.edit')
              %li.list-inline-item
                = link_to admin_work_path(work), method: :delete, data: { confirm: t('admin.btn.destroy_confirm') }, class: 'btn btn-sm btn-outline-danger mb-sm-0' do
                  %i.fa.fa-ban.fa-fw
                  = t('admin.btn.destroy')
= render 'admin/shared/pagy'

app/views/admin/works/_work_creator_fields.html.haml
.nested-fields.form-row.align-items-center.mb-3.mb-sm-1
  .col-sm-1.js-guest-checkbox-wrapper
    .form-row.custom-control.custom-checkbox
      .col-2.d-sm-none
        %legend.text-md.col-form-label-sm.d-none.d-sm-inline= WorkCreator.human_attribute_name :guest
      .col-10.col-sm-12
        = f.check_box :guest, class: 'custom-control-input js-guest-checkbox'
        = f.label :guest, class: 'custom-control-label mb-1 mb-sm-0' do
          %span.col-form-label-sm.d-none.d-xl-inline.text-nowrap= WorkCreator.human_attribute_name :guest
  .col-sm-3
    .form-row
      .col-2.d-sm-none= f.label :role, class: 'col-form-label-sm'
      .col-10.col-sm-12
        = f.collection_select :role, WorkCreator.roles, :first, ->(s) { WorkCreator.human_attribute_enum_value :role, s.first },
          { include_blank: true }, class: 'form-control form-control-sm'
  .col-sm-3.js-creator-select-wrapper
    .form-row
      .col-2.d-sm-none= f.label :creator_id, class: 'col-form-label-sm'
      .col-10.col-sm-12
        = f.collection_select :creator_id, creators, :id, :name, { include_blank: true }, class: 'form-control form-control-sm js-creator-select', disabled: f.object.guest?
  .col-sm-3.js-name-field-wrapper
    .form-row
      .col-2.d-sm-none= f.label :name, class: 'col-form-label-sm'
      .col-10.col-sm-12= f.text_field :name, class: 'form-control form-control-sm js-name-field', disabled: !f.object.guest?
  .col-sm-2
    .d-sm-flex.align-items-center
      .form-row.flex-grow-1.mr-sm-1
        .col-2.d-sm-none= f.label :xorder, class: 'col-form-label-sm'
        .col-10.col-sm-12= f.number_field :xorder, class: 'form-control form-control-sm'
      = link_to_remove_association f, class: 'text-danger' do
        .text-right.text-sm-left
          %i.fa.fa-times.fa-fw
          %span.d-sm-none= t('admin.btn.destroy')

app/views/admin/works/edit.html.haml
- breadcrumb :edit_admin_work, @work
%h1.page-title= t('admin.page_title.edit', model: Work.model_name.human)
= render 'form', work: @work

app/views/admin/works/index.html.haml
- breadcrumb :admin_works
%h1.page-title= t('admin.page_title.index', model: Work.model_name.human)
.btn-area
  = link_to new_admin_work_path, class: 'btn btn-primary' do
    %i.fa.fa-plus.fa-fw
    = t('admin.btn.new')
= render 'table', works: @works

app/views/admin/works/new.html.haml
- breadcrumb :new_admin_work, @work
%h1.page-title= t('admin.page_title.new', model: Work.model_name.human)
= render 'form', work: @work

app/views/admin/works/show.html.haml
- breadcrumb :admin_work, @work
%h1.page-title= @work.title
%ul.list-inline.btn-area
  %li.list-inline-item
    = link_to edit_admin_work_path(@work), class: 'btn btn-primary' do
      %i.fa.fa-edit.fa-fw
      = t('admin.btn.edit')
  %li.list-inline-item
    = link_to admin_work_path(@work), method: :delete, data: { confirm: t('admin.btn.destroy_confirm') }, class: 'btn btn-outline-danger' do
      %i.fa.fa-ban.fa-fw
      = t('admin.btn.destroy')
- if @work.eye_catch.attached?
  = image_tag @work.eye_catch.variant(resize_to_fill: Work::EYE_CATCH_SIZES[:default]), alt: t('admin.label.eye_catch', title: @work.title), class: 'eye-catch--default mb-4'
.table-responsive
  %table.table.table-bordered.table__th--min.table-middle
    %colgroup
    %tr
      %th ID
      %td= @work.id
    %tr
      %th= Work.human_attribute_name :title
      %td.font-weight-bold= @work.title
    %tr
      %th= Work.human_attribute_name :parent
      %td
        - if @work.parent.present?
          = link_to @work.parent.title, admin_work_path(@work.parent)
        - else
          .text-muted= t('admin.label.none')
    %tr
      %th= Work.human_attribute_name :children
      %td
        - if @work.children.present?
          %ul.mb-0
            - @work.children.each do |child|
              %li= link_to child.title, admin_work_path(child)
        - else
          .text-muted= t('admin.label.none')
    %tr
      %th= Work.human_attribute_name :status
      %td= @work.human_attribute_enum :status
    %tr
      %th= Work.human_attribute_name :slug
      %td
        %code= @work.slug
    %tr
      %th= Work.human_attribute_name :release_date
      %td= l @work.release_date if @work.release_date.present?
    %tr
      %th= Work.human_attribute_name :content
      %td= @work.content
    %tr
      %th= Work.human_attribute_name :work_creators
      %td= render 'creator_list', work: @work
    %tr
      %th= Work.human_attribute_name :like
      %td= @work.like.to_s(:delimited)